"""initial schema

Revision ID: 4bd824fc5d20
Revises: 
Create Date: 2026-03-12 18:49:35.367220

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4bd824fc5d20'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('empresas',
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('dominio', sa.String(length=200), nullable=True),
    sa.Column('plano', sa.String(length=50), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('r2_bucket_name', sa.String(length=200), nullable=True),
    sa.Column('r2_access_key', sa.Text(), nullable=True),
    sa.Column('r2_secret_key', sa.Text(), nullable=True),
    sa.Column('r2_public_url', sa.String(length=500), nullable=True),
    sa.Column('webhook_leads', sa.String(length=1000), nullable=True),
    sa.Column('webhook_secret', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deletado_em', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('arquivos',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('empresa_id', sa.UUID(), nullable=False),
    sa.Column('nome_original', sa.String(length=500), nullable=True),
    sa.Column('nome_arquivo', sa.String(length=500), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('tamanho_bytes', sa.BigInteger(), nullable=True),
    sa.Column('largura', sa.Integer(), nullable=True),
    sa.Column('altura', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deletado_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('banners',
    sa.Column('empresa_id', sa.UUID(), nullable=False),
    sa.Column('titulo', sa.String(length=500), nullable=True),
    sa.Column('subtitulo', sa.String(length=500), nullable=True),
    sa.Column('texto', sa.Text(), nullable=True),
    sa.Column('label_cta', sa.String(length=100), nullable=True),
    sa.Column('link_cta', sa.String(length=1000), nullable=True),
    sa.Column('imagem_url', sa.String(length=1000), nullable=True),
    sa.Column('imagem_mobile', sa.String(length=1000), nullable=True),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deletado_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('categorias',
    sa.Column('empresa_id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deletado_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('empresa_id', 'slug', 'tipo', name='uq_categorias_empresa_slug_tipo')
    )
    op.create_table('configuracoes',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('empresa_id', sa.UUID(), nullable=False),
    sa.Column('secao', sa.String(length=100), nullable=False),
    sa.Column('chave', sa.String(length=100), nullable=False),
    sa.Column('valor', sa.Text(), nullable=True),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('empresa_id', 'secao', 'chave', name='uq_config_empresa_secao_chave')
    )
    op.create_table('contatos',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('empresa_id', sa.UUID(), nullable=False),
    sa.Column('telefone', sa.String(length=30), nullable=True),
    sa.Column('telefone_2', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('whatsapp', sa.String(length=30), nullable=True),
    sa.Column('whatsapp_hover', sa.String(length=200), nullable=True),
    sa.Column('endereco', sa.Text(), nullable=True),
    sa.Column('cidade', sa.String(length=200), nullable=True),
    sa.Column('estado', sa.String(length=2), nullable=True),
    sa.Column('cep', sa.String(length=9), nullable=True),
    sa.Column('mapa_embed', sa.Text(), nullable=True),
    sa.Column('facebook', sa.String(length=500), nullable=True),
    sa.Column('instagram', sa.String(length=500), nullable=True),
    sa.Column('linkedin', sa.String(length=500), nullable=True),
    sa.Column('youtube', sa.String(length=500), nullable=True),
    sa.Column('tiktok', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('empresa_id')
    )
    op.create_table('depoimentos',
    sa.Column('empresa_id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('cargo', sa.String(length=200), nullable=True),
    sa.Column('empresa', sa.String(length=200), nullable=True),
    sa.Column('texto', sa.Text(), nullable=False),
    sa.Column('foto_url', sa.String(length=1000), nullable=True),
    sa.Column('nota', sa.Integer(), nullable=True),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deletado_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('destaques',
    sa.Column('empresa_id', sa.UUID(), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('icone_url', sa.String(length=1000), nullable=True),
    sa.Column('icone_svg', sa.Text(), nullable=True),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deletado_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('empresa_modulos',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('empresa_id', sa.UUID(), nullable=False),
    sa.Column('modulo', sa.String(length=50), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('empresa_id', 'modulo', name='uq_empresa_modulo')
    )
    op.create_table('equipe',
    sa.Column('empresa_id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('cargo', sa.String(length=200), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('foto_url', sa.String(length=1000), nullable=True),
    sa.Column('linkedin', sa.String(length=500), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deletado_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('faq',
    sa.Column('empresa_id', sa.UUID(), nullable=False),
    sa.Column('pergunta', sa.String(length=500), nullable=False),
    sa.Column('resposta', sa.Text(), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deletado_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('galeria',
    sa.Column('empresa_id', sa.UUID(), nullable=False),
    sa.Column('titulo', sa.String(length=300), nullable=True),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deletado_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('temas',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('empresa_id', sa.UUID(), nullable=False),
    sa.Column('tema_slug', sa.String(length=50), nullable=False),
    sa.Column('cor_primaria', sa.String(length=7), nullable=False),
    sa.Column('cor_secundaria', sa.String(length=7), nullable=False),
    sa.Column('cor_destaque', sa.String(length=7), nullable=False),
    sa.Column('cor_texto', sa.String(length=7), nullable=False),
    sa.Column('cor_fundo', sa.String(length=7), nullable=False),
    sa.Column('cor_header', sa.String(length=7), nullable=False),
    sa.Column('cor_footer', sa.String(length=7), nullable=False),
    sa.Column('fonte_principal', sa.String(length=100), nullable=False),
    sa.Column('fonte_titulo', sa.String(length=100), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios',
    sa.Column('empresa_id', sa.UUID(), nullable=True),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('senha_hash', sa.Text(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('ultimo_acesso', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deletado_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('audit_log',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('empresa_id', sa.UUID(), nullable=True),
    sa.Column('usuario_id', sa.UUID(), nullable=True),
    sa.Column('acao', sa.String(length=50), nullable=False),
    sa.Column('tabela', sa.String(length=100), nullable=True),
    sa.Column('registro_id', sa.UUID(), nullable=True),
    sa.Column('dados_antes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('dados_depois', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('itens',
    sa.Column('empresa_id', sa.UUID(), nullable=False),
    sa.Column('tipo_label', sa.String(length=100), nullable=False),
    sa.Column('nome', sa.String(length=500), nullable=False),
    sa.Column('slug', sa.String(length=500), nullable=False),
    sa.Column('resumo', sa.Text(), nullable=True),
    sa.Column('descricao', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('imagem_url', sa.String(length=1000), nullable=True),
    sa.Column('imagens', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('categoria_id', sa.UUID(), nullable=True),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('versao', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deletado_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias.id'], ),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('leads',
    sa.Column('empresa_id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('telefone', sa.String(length=30), nullable=True),
    sa.Column('mensagem', sa.Text(), nullable=True),
    sa.Column('origem', sa.String(length=500), nullable=True),
    sa.Column('ip_origem', sa.String(length=45), nullable=True),
    sa.Column('respondido', sa.Boolean(), nullable=False),
    sa.Column('respondido_em', sa.DateTime(), nullable=True),
    sa.Column('respondido_por', sa.UUID(), nullable=True),
    sa.Column('lgpd_aceito', sa.Boolean(), nullable=False),
    sa.Column('lgpd_aceito_em', sa.DateTime(), nullable=True),
    sa.Column('lgpd_ip', sa.String(length=45), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deletado_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['respondido_por'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('posts',
    sa.Column('empresa_id', sa.UUID(), nullable=False),
    sa.Column('tipo', sa.String(length=30), nullable=False),
    sa.Column('titulo', sa.String(length=500), nullable=False),
    sa.Column('slug', sa.String(length=500), nullable=False),
    sa.Column('resumo', sa.Text(), nullable=True),
    sa.Column('conteudo', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('imagem_capa', sa.String(length=1000), nullable=True),
    sa.Column('categoria_id', sa.UUID(), nullable=True),
    sa.Column('autor', sa.String(length=200), nullable=True),
    sa.Column('publicado', sa.Boolean(), nullable=False),
    sa.Column('publicado_em', sa.DateTime(), nullable=True),
    sa.Column('meta_title', sa.String(length=70), nullable=True),
    sa.Column('meta_desc', sa.String(length=160), nullable=True),
    sa.Column('og_image', sa.String(length=1000), nullable=True),
    sa.Column('og_title', sa.String(length=200), nullable=True),
    sa.Column('canonical_url', sa.String(length=1000), nullable=True),
    sa.Column('indexavel', sa.Boolean(), nullable=False),
    sa.Column('versao', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deletado_em', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias.id'], ),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('empresa_id', 'slug', name='uq_posts_empresa_slug')
    )
    op.create_table('refresh_tokens',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.Text(), nullable=False),
    sa.Column('ip', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('expira_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revogado', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_table('usuario_permissoes',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('modulo', sa.String(length=50), nullable=False),
    sa.Column('pode_ver', sa.Boolean(), nullable=False),
    sa.Column('pode_criar', sa.Boolean(), nullable=False),
    sa.Column('pode_editar', sa.Boolean(), nullable=False),
    sa.Column('pode_deletar', sa.Boolean(), nullable=False),
    sa.Column('pode_exportar', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id', 'modulo', name='uq_usuario_modulo')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usuario_permissoes')
    op.drop_table('refresh_tokens')
    op.drop_table('posts')
    op.drop_table('leads')
    op.drop_table('itens')
    op.drop_table('audit_log')
    op.drop_table('usuarios')
    op.drop_table('temas')
    op.drop_table('galeria')
    op.drop_table('faq')
    op.drop_table('equipe')
    op.drop_table('empresa_modulos')
    op.drop_table('destaques')
    op.drop_table('depoimentos')
    op.drop_table('contatos')
    op.drop_table('configuracoes')
    op.drop_table('categorias')
    op.drop_table('banners')
    op.drop_table('arquivos')
    op.drop_table('empresas')
    # ### end Alembic commands ###
